Favorite_Books/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]

app1/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = 'app1'

urlpatterns = [
    path('', views.registration, name='registration'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('home', views.home, name='home'),
    path('add_book', views.add_book, name='add_book'),
    path('book/<int:pk>', views.book, name='book'),
    path('add_to_favorite/<int:pk>', views.add_to_favorite, name='add_to_favorite'),
    path('remove_from_favorite/<int:pk>', views.remove_from_favorite, name='remove_from_favorite'),
    path('update/<int:pk>', views.updated, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),

]

app1/models.py
from django.db import models


#this for validation
class BooksManger(models.Manager):
    def validate(self, post_data):
        errors = {}
        if len(post_data['description']) < 5:
            errors['description'] = 'Description should be at least 5 charters'
        return errors
    
class Books(models.Model):
    uploaded_by = models.ForeignKey('Users', on_delete=models.CASCADE)
    title= models.CharField(max_length=255)
    description=models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    objects = BooksManger()
    
    def __str__(self):
        return str({self.title})




#this for validation
class UsersManger(models.Manager):
    def validate(self, post_data):
        errors = {}
        if len(post_data['first_name']) < 2:
            errors['first_name'] = 'First name should be at least 2 charters'
        if len(post_data['last_name']) < 2:
            errors['last_name'] = 'Last name should be at least 2 charters'    
        if len(post_data['password1']) < 8:
            errors['password1'] = 'Password should be at least 8 charters'
        return errors


class Users(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email= models.EmailField(unique=True)
    password = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    favorite_books = models.ManyToManyField(Books)
    objects = UsersManger()


    def __str__(self):
        return str({self.first_name,self.last_name,self.email})

app1/views.py
from django.shortcuts import render,redirect
from .models import Users,Books
from django.contrib import messages
import bcrypt

def registration(request):
    user_id = request.session.get('user_id')
    
    if user_id:
        return redirect('app1:home')
    
    return render(request, "registration.html") 


def register(request):
    if request.method == "POST":
        
        errors = Users.objects.validate(request.POST)
        
        # There is some errors
        if len(errors) > 0:
            for error in errors.values():
                messages.error(request, error)
            return redirect('app1:registration')
        
        first_name_form = request.POST['first_name']
        last_name_form = request.POST['last_name']
        email_form = request.POST['email']
        password_form = request.POST['password1']
        confirm_password_form = request.POST['password2']
        
        if password_form == confirm_password_form:
            hash_password = bcrypt.hashpw(password_form.encode(), bcrypt.gensalt()).decode()
            
            new_user =Users.objects.create(
                first_name=first_name_form,
                last_name = last_name_form,
                email=email_form,
                password=hash_password)
            
            
            request.session['user_id'] = new_user.id
            request.session['first_name'] = new_user.first_name

            return redirect('app1:home')

        # if password didn't match
        else:
            messages.error(request, 'Password not match.')
            return redirect('app1:registration')



def login(request):
    if request.method == "POST":
        email_form = request.POST['email']
        password_form = request.POST['password1']
        
        users = Users.objects.filter(email=email_form)
        
        if len(users) == 0:
            messages.error(request, "Email doesn't exist.")
            return redirect('app1:registration')
        
        if bcrypt.checkpw(password_form.encode(), users.first().password.encode()):
            request.session['user_id'] = users[0].id
            request.session['first_name'] = users[0].first_name

            
            return redirect('app1:home')
        # if password is wrong
        else:
            messages.error(request, 'Password not correct.')
            return redirect('app1:registration')



def logout(request):
    request.session.flush()
    return redirect('app1:registration')


def home(request):
    user_id = request.session.get('user_id')
    # if user not logged in
    if not user_id:
        return redirect('app1:registration')
    
    all_books = Books.objects.all().order_by('-updated_at')
    current_user = Users.objects.get(id=user_id)
    
    context = {
        'books' : all_books,
        'user': current_user
    }    
    return render(request, "home.html", context)


def add_book(request):
    errors = Books.objects.validate(request.POST)
    if len(errors) > 0:
            for error in errors.values():
              messages.error(request, error)      #هان كأنه عملنا كونتكس عشان يزهر في تمبلت 

            return redirect('app1:registration')
        
    title = request.POST['title']
    description = request.POST['description']



# for create new book  we  get the user first and do that:لازم اجيب اليوزر عشان اعمل كريات بووك 
    user_id = request.session['user_id']
    user = Users.objects.get(id=user_id)
    
    book = Books.objects.create(title=title, description=description, uploaded_by=user)
    
    # To add book to user favorite books
    user.favorite_books.add(book)
    return redirect('app1:home')


def book(request, pk):
    book_to_view = Books.objects.get(id=pk)
    current_user = Users.objects.get(id=request.session['user_id'])
    
    context = {
        'book': book_to_view,
        'user': current_user
    }
    
    if book_to_view.uploaded_by == current_user:
        return render(request, 'if_uploaded_by.html', context)

    return render(request, "if_not_uploaded_by.html", context)


def add_to_favorite(request, pk):
    user = Users.objects.get(id=request.session['user_id'])
    book = Books.objects.get(id=pk)
    user.favorite_books.add(book)
    return redirect('app1:home')


def remove_from_favorite(request, pk):
    user = Users.objects.get(id=request.session['user_id'])
    book = Books.objects.get(id=pk)
    user.favorite_books.remove(book)
    return redirect('app1:home')

def updated(request, pk):
    title = request.POST['title']
    description = request.POST['description']
    
    book = Books.objects.get(id=pk)
    
    book.title = title
    book.description = description
    book.save()
    return redirect('app1:home',)


def delete(request, pk):
    book = Books.objects.get(id=pk)
    book.delete()
    return redirect('app1:home')

app1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Favorite books </title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="../static/btnstyle.css">

  </head>
   <body>
    
  <div class="container text-left mt-6">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page"href="{% url 'app1:home'%}">Welcome , {{request.session.first_name}} !</a>
                </li>
              </ul>
                              <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">
                    
                                        
                                        <li class="nav-item ">
                                            <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"  href="{% url 'app1:logout' %}">Log out</a>
                                        </li>

                              </ul>
           
          </div>
        </div>
      </nav>
      <hr>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>



</div>
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</body>
</html>

app1/templates/home.html
{% extends './base.html' %}
{% block content %}
<link rel="stylesheet" href="../static/btnstyle.css">


<div class="container text-left mt-6">
  <div class=" row ">
<div class="col-lg-6">
  <div class=" ">

  <h2>Add a favorite book</h2>
  <form class="add_Form" action="{% url 'app1:add_book' %}" method="POST" >
    {% csrf_token %}
  <!-- Title Input > type :"text" -->
  <div class="d-flex align-items-center gap-2 mb-3">
    <label for="title" class="col-sm-2 col-form-label">Title : </label>
    <div style="flex: 1.4" class="col-sm-4">
      <input required type="text" name="title" class="form-control w-50" id="title">
    </div>
  </div>
  
  <!-- Description Input > type :"textarea" -->
  <div class="form-group d-flex">
    <label for="exampleFormControlTextarea1" class="me-2">Description : </label>
    <textarea class="form-control w-50 " name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
  <div class="submit-btn d-flex justify-content-center ">

    <button style="width: fit-content;
            box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
            , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
            border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3"> Add</button>


</form>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}


</div>
</div>
</div> 




<div class="col-lg-6">
<div class="right_side">
  <h2>All Books</h2>
    
    {% for book in books %}
    <p><a  style="text-decoration: underline;" class="link text-primary" href="{% url 'app1:book' pk=book.pk %}">{{book.title}}</a></p>
    <p>{{book.uploaded_by.first_name}}</p>
    
    {% if book in user.favorite_books.all %}
    <p>This is one of your favorite books!</p>
    {% else %}
    <a style="text-decoration: underline;" href="{% url 'app1:add_to_favorite' pk=book.pk %}">Add to Favorites</a>
    {% endif %}
    <br>
    <hr>
    {% endfor %}
  </div>
</div>

</div>
</div>





















{% endblock content %}

app1/templates/if_not_uploaded_by.html
{% extends './base.html' %}
{% block content %}
<div class="container text-left mt-6">
    
        <div class="row mt-5">
            <div class=" col-lg-6">
                <h1 class="book_title  h3 w-75 border-0 ">{{ book.title}} </h1>
                <div>
    
                    <p>Added by: {{book.uploaded_by.first_name}}</p>
                    <p>Added on: {{book.created_at}}</p>
                    <p>Last updated on: {{book.updated_at}}</p>
                    <p>Description: {{book.description}} </p>
                    
                </div>
            </div>
            <div class=" col-lg-6">
<div class= "pairent">
    <h1 class="h3">Users Who Like This Book:</h1>
    {% for user in book.users_set.all %}

    <p> . {{user.first_name}}
        
    </p>
    {% endfor %}

    {% if book in user.favorite_books.all %}
        <a  class="un_favorite" style="text-decoration: underline;" href="{% url 'app1:remove_from_favorite' pk=book.pk %}">Un Favorites</a>
    {% else %}
        <a style="text-decoration: underline;" href="{% url 'app1:add_to_favorite' pk=book.pk %}">Add to Favorites</a>
    {% endif %}
</div>
            </div>
      
        </div>

</div>
{% endblock content %}

app1/templates/if_uploaded_by.html
{% extends './base.html' %}
{% block content %}
<div class="container text-left mt-6">
    
        <div class="row mt-5">
            <div class=" col-lg-6">
                <div>
    
                    
                    <form action="{% url 'app1:update' pk=book.id  %}" method="POST">
                        {% csrf_token %}
                            <input required type="text" name="title" class="rounded border-3 w-75 " id="title" value="{{ book.title }}">                    <br>
                            <p>Added by: {{book.uploaded_by.first_name}}</p>
                            <p>Added on: {{book.created_at}}</p>
                            <p>Last updated on: {{book.updated_at}}</p>
                            <div class="form-group d-flex  ">
                            <label for="exampleFormControlTextarea1" class="me-2">Description :   </label>
                            <textarea class=""  name="description" id="exampleFormControlTextarea1" rows="5" cols="35">{{ book.description }}</textarea>
                        </div>
                          <div class="btn_div d-flex justify-content-center">
                            <button style="width: fit-content;
                            box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
                            , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
                            border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3"> Update</button>
                                <button style="width: fit-content;
                                box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
                                , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
                                border: 2px solid black;" class="btn btn-outline-dark btn-shadow mt-3  text-light bg-danger"> <a   class="dec text-decoration-none text-white"   href="{% url 'app1:delete' pk=book.id  %}">Delete</a></button>
                 
                          </div>
                            </form>
                    
                </div>
            </div>
            <div class=" col-lg-6">
<div class= "pairent">
    <h1 class="h3">Users Who Like This Book:</h1>
    {% for user in book.users_set.all %}

    <p> . {{user.first_name}}
        
    </p>
    {% endfor %}

    {% if book in user.favorite_books.all %}
        <a  class="un_favorite" style="text-decoration: underline;" href="{% url 'app1:remove_from_favorite' pk=book.pk %}">Un Favorites</a>
    {% else %}
        <a style="text-decoration: underline;" href="{% url 'app1:add_to_favorite' pk=book.pk %}">Add to Favorites</a>
    {% endif %}
</div>
            </div>
      
        </div>

</div>
{% endblock content %}

app1/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login & Registration</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
  </head>
   <body>
    
  <div class="container text-left mt-6">


      
      <div class="row mt-5">
        <div class="col-lg-6">
          <h1>Registration</h1>
      <br>
      <form action="{% url 'app1:register' %}" method="POST" class="d-flex flex-column gap-3 ">
        {% csrf_token %}
         <!-- Name Input > type :"text" -->
         <div class="d-flex align-items-center gap-2">
          <label for="first_name" class="col-sm-2 col-form-label"> First name : </label>
          <div style="flex: 1.4" class="col-sm-4">
            <input required type="text" name="first_name" class="form-control" id="first_name">
          </div>
        </div>
         <!-- Name Input > type :"text" -->
         <div class="d-flex align-items-center gap-2">
          <label for="last_name" class="col-sm-2 col-form-label"> Last name : </label>
          <div style="flex: 1.4" class="col-sm-4">
            <input required type="text" name="last_name" class="form-control" id="last_name">
          </div>
        </div>
          <!-- email Input > type :type="email" -->
          <div class="d-flex align-items-center gap-2">
            <label for="inputEmail3" class="col-sm-2 col-form-label"> Email : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="email" name="email" class="form-control" id="email">
            </div>
          </div>
          <!-- email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password1" class="col-sm-2 col-form-label"> Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
             <input required type="password" name="password1" class="form-control" id="password1">
            </div>
          </div>

          <!-- confirm email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password2" class="col-sm-2 col-form-label">  Confirm Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
             <input required type="password" name="password2" class="form-control" id="password2">
            </div>
          </div>
        <!-- {{registration_form}} -->
        <button style="width: fit-content;
          box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
          , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
          border: 2px solid black;"
        type="submit" class="btn btn-outline-dark mt-3"> Registr</button>
      </form>

        </div>
        <div class="col-lg-6">
          <h1>Log in </h1>
          <br>
          <form action="{% url 'app1:login' %}" method="POST" class="d-flex flex-column gap-3 ">
            {% csrf_token %}
             <!-- email Input > type :type="email" -->
          <div class="d-flex align-items-center gap-2">
            <label for="inputEmail3" class="col-sm-2 col-form-label"> Email : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="email" name="email" class="form-control" id="email">
            </div>
          </div>
          <!-- email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password1" class="col-sm-2 col-form-label"> Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
             <input required type="password" name="password1" class="form-control" id="password1">
            </div>
          </div>
    
            <!-- {{login_form}} -->
            <button style="width: fit-content;
            box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
            , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
            border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3"> Login </button>
          </form>
        </div>
      </div> 
  </div>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
  </body>
</html>